<?php
$site_url="http://demo301.phpcaiji.com";
$site_title="单域名克隆版";
$target_url="http://baike.so.com";
$target_title="360百科";
$capture_mode="0";
$anti_theft="0";
$user_curl="1";
$user_agent="bing";
$user_client="pc";
$charset="gb2312";
$nochange="doc|rar|zip";
$change_link="0";
$link_name="link.php";
$url_encode="0";
$nochange_url="127.0.0.1|qhimg.com";
$cache_path="cache";
$cache_suffix=".cache";
$cache_time="0";
$gzip="0";
$shield_spider="1";
$spider_name="youdao|yahoo";
$license_code="";
?>